apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  namespace: demo1
spec:
  type: NodePort
  ports:
    - port: 8090
      targetPort: 8090
      nodePort: 32752
  selector:
    name: tomcat
