apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: demo1
  labels:
    name: nginx-deployment
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
        labels: 
          name: nginx
    spec:
      containers:
      - image: amdali/nginx-deployment
        name:  nginx-container
        ports:
        - containerPort:  8080
          name:  nginx-web-port
      restartPolicy: Always
