apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  sample-webapp
  namespace: demo1
  labels:
    name: sample-webapp
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
        labels:
          name: tomcat
    spec:
      containers:
      - image: tomcat:8.0
        name:  tomcat-container
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort:  8090
          name:  tomcat-port
      restartPolicy: Always
