apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  namespace: backbase
  labels:
    name: tomcat-deployment
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
        labels: 
          name: tomcat
    spec:
      containers:
      - image: tomcat:8.0
        name: sample-webapp-tomcat
        ports:
        - containerPort:  8090
          name:  port-8090-tcp
      restartPolicy: Always
